from enum import Enum

class UGG(Enum):
    """Auto-generated enum: Source"""
    TERNEROS_MENORES_1_ANIO = "TERNEROS_MENORES_1_ANIO"
    HEMBRAS_MACHOS_1_2_ANIOS = "HEMBRAS_MACHOS_1_2_ANIOS"
    HEMBRAS_MENORES_2_3_ANIOS = "HEMBRAS_MENORES_2_3_ANIOS"
    MACHOS_2_3_ANIOS = "MACHOS_2_3_ANIOS"
    HEMBRAS_MAYORES_3_ANIOS = "HEMBRAS_MAYORES_3_ANIOS"
    MACHOS_MAYORES_3_ANIOS = "MACHOS_MAYORES_3_ANIOS"
